# Generated by Django 4.1.3 on 2022-11-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
